# Generated by Django 5.1.3 on 2024-12-04 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_subproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subproduct',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app.subproduct'),
        ),
    ]
