# Generated by Django 5.1.3 on 2024-12-05 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_subproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subproduct',
        ),
        migrations.AddField(
            model_name='subproduct',
            name='subproduct',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
