# Generated by Django 5.1.3 on 2024-12-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_product_subproduct_subproduct_subproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproduct',
            old_name='subproduct',
            new_name='Product',
        ),
    ]
