# Generated by Django 5.1.3 on 2024-12-05 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_subproduct_subproduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproduct',
            old_name='Product',
            new_name='product',
        ),
    ]
