# Generated by Django 5.1.3 on 2024-12-05 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_subproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='subproduct',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app.subproduct'),
        ),
    ]
