# Generated by Django 5.1.3 on 2024-12-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_product_subproduct_subproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='flowerorde/png'),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='flowerorde/png'),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='flowerorde/videos'),
        ),
        migrations.CreateModel(
            name='MainSubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='flowerorde/png')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('mainproduct', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app.mainproduct')),
            ],
        ),
    ]
