# Generated by Django 5.1.3 on 2024-12-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_mainproduct_image2_mainproduct_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLastProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='flowerorde/png')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('lastProduct', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app.lastproduct')),
            ],
        ),
    ]
