# Generated by Django 5.1.3 on 2024-12-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_sublastproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsubproduct',
            name='price',
        ),
    ]
